# Generated by Django 3.2 on 2023-03-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='has_enter_before',
            field=models.BooleanField(default=False),
        ),
    ]
