# Generated by Django 3.2 on 2023-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='intereses',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='logros_y_trofeos',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
