# Generated by Django 3.2 on 2023-05-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230427_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
