# Generated by Django 3.2 on 2023-03-15 14:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_has_enter_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='juegos_favoritos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
