# Generated by Django 3.2 on 2023-03-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20230316_0350'),
        ('accounts', '0003_useraccount_juegos_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='juegos_favoritos',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='favorite_games',
            field=models.ManyToManyField(to='games.Game'),
        ),
    ]
