# Generated by Django 3.2 on 2023-03-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230316_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='age',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_photo',
            field=models.CharField(default='', max_length=250),
        ),
    ]
