# Generated by Django 3.2 on 2023-03-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230320_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='about_me',
            field=models.TextField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
