# Generated by Django 3.2 on 2023-05-28 21:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccount_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_to),
        ),
    ]
