# Generated by Django 3.2 on 2023-03-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraccount_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='about_me',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
