# Generated by Django 3.2 on 2023-05-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('accounts', '0006_auto_20230528_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='blocked_games',
            field=models.ManyToManyField(related_name='blocked_by', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='favorite_games',
            field=models.ManyToManyField(related_name='favorited_by', to='games.Game'),
        ),
    ]
