# Generated by Django 3.2 on 2023-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_game', models.IntegerField(blank=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('ano_lanzamiento', models.PositiveIntegerField(default=None)),
                ('genero', models.CharField(max_length=255)),
                ('plataforma', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=250)),
            ],
        ),
    ]
