# Generated by Django 3.2 on 2023-03-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20230316_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
