# Generated by Django 3.2 on 2023-03-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
        migrations.AddField(
            model_name='game',
            name='ano_lanzamiento',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='game',
            name='descripcion',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='genero',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='plataforma',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='titulo',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
