# Generated by Django 3.2 on 2023-05-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
    ]
