# Generated by Django 3.2 on 2023-05-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_match_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_successful',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
