# Generated by Django 3.2 on 2023-03-23 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendlist', '0002_amigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
