# Generated by Django 3.2 on 2023-04-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendlist', '0003_auto_20230322_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigo',
            name='estado',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
